# Phiên bản render.yaml sử dụng Docker Image chuẩn cho Laravel
services:
  # Dịch vụ Web Laravel
  - type: web
    name: bookhaven-app
    # SỬA Ở ĐÂY: Thay 'env: php' bằng 'runtime: docker'
    runtime: docker
    # Chỉ định Dockerfile sẽ được sử dụng để build môi trường
    dockerfilePath: ./Dockerfile 
    # Khai báo các biến môi trường
    envVars:
      - key: APP_URL
        value: https://${RENDER_EXTERNAL_URL}
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      
      # --- Các biến kết nối tới Aiven ---
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL_CA
        value: ca.pem
